FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y bash wget jq sshpass
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y openssh-client

COPY commands/check /opt/resource/check
COPY commands/in /opt/resource/in
COPY commands/out /opt/resource/out
