#!/bin/bash

set -e

exec 3>&1 # use fd 3 for script output
exec 1>&2 # send normal stdout to stderr for logging

input=$(mktemp /tmp/resource-in.XXXXXX)
cat > "${input}" <&0

host=$(jq -r '.source.host // empty' $input)
username=$(jq -r '.source.username // empty' $input)
private_key=$(jq -r '.source.private_key // empty' $input)
source_dir=$(jq -r '.source.source_dir // empty' $input)
password=$(jq -r '.source.password // empty' $input)

# check for config errors //Begin
if [[ -z ${host} ]]; then
  error="$(cat <<EOF
[{"error": "host must be set"}]
EOF
)"
  echo "${error}" | jq -s add >&3
  exit 1
elif [[ -z ${username} ]]; then
  error="$(cat <<EOF
[{"error": "username must be set"}]
EOF
)"
  echo "${error}" | jq -s add >&3
  exit 1
elif [[ -z ${source_dir} ]]; then
  error="$(cat <<EOF
[{"error": "source_dir must be set"}]
EOF
)"
  echo "${error}" | jq -s add >&3
  exit 1
elif [[ ! -z ${private_key} ]]; then # return error if both private_key and password is set.
  if [[ ! -z ${password} ]]; then 
    error="$(cat <<EOF
[{"error": "Only one of private_key or password should be set"}]
EOF
)"
    echo "${error}" | jq -s add >&3
    exit 1
  fi
elif [[ -z ${private_key} ]]; then # return error if none of private_key and password is set.
  if [[ -z ${password} ]]; then 
    error="$(cat <<EOF
[{"error": "One of private_key or password should be set"}]
EOF
)"
    echo "${error}" | jq -s add >&3
    exit 1
  fi
fi
# check for config errors //End

if [[ ! -z ${private_key} ]]; then
  echo "${private_key}" > private_key.pem
  chmod 0600 private_key.pem

  md5checksum=$(ssh -i private_key.pem -o StrictHostKeyChecking=no $username@$host "find $source_dir -type f -exec md5sum {} + | awk '{print $1}' | sort | md5sum")
else
  md5checksum=$(sshpass -p ${password} ssh -o StrictHostKeyChecking=no $username@$host "find $source_dir -type f -exec md5sum {} + | awk '{print $1}' | sort | md5sum")
fi

version="$(cat <<EOF
[
    {
        "version": "${md5checksum}"
    }
]
EOF
)"

#echo '[{"version": "1.0"}]'

echo "$version" | jq -s add >&3
#echo '{"version":{"ref":"none"}}'
